theme = "tokyonight-transparent"

[editor]
line-number = "relative"
rulers = [120]
end-of-line-diagnostics = "hint"
true-color = true
color-modes = true
path-completion = true
# insert = "bar"
# normal = "block"
# select = "block"
gutters = ["diagnostics", "line-numbers", "diff"]

[editor.soft-wrap]
enable = true

[editor.auto-save]
focus-lost  = true
after-delay.enable = true
after-delay.timeout = 300000

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",

]
center = []
right = [
  "diagnostics",
  "workspace-diagnostics",
  "position",
  "total-line-numbers",
  "position-percentage",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "register",
  "selections",
]
separator = "│"

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.indent-guides]
render = true
character = "│"
skip-levels = 0

[keys.normal]
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"
P = "paste_clipboard_after"
d = ["yank_main_selection_to_clipboard", "delete_selection"]
c = ["yank_main_selection_to_clipboard", "change_selection"]
K = "hover"
H = "goto_previous_buffer"
L = "goto_next_buffer"

[keys.select]
y = "yank_main_selection_to_clipboard"
p = "replace_selections_with_clipboard"
d = ["yank_main_selection_to_clipboard", "delete_selection"]
ret = "expand_selection"
backspace = "shrink_selection"
del = "delete_selection"

[keys.normal.space]
p = "paste_clipboard_before"
P = "paste_clipboard_after"
x = ":buffer-close"

[keys.insert]
"j" = { "k" = "normal_mode" }

[keys.normal.space.f]
f = "file_picker_in_current_directory"
F = "file_picker"
b = "file_picker_in_current_buffer_directory"
"." = ":toggle-option file-picker.git-ignore"
g = "global_search"
r = ":reload-all"
x = ":reset-diff-change"
